print ('o joão pedro é lindo')
Num1 = int (input('Digite um numero: '))
Num2 = int (input('Digite um numero: '))
print ('o resultado da merda de',Num1,'+',Num2,'é:',Num1+Num2)
print ('era só isso mesmo')
